- name: Fetch last updates from apt history log
  hosts: all
  tasks:
    - name: Read last 20 lines of apt history
      shell: "tail -n 20 /var/log/apt/history.log"
      register: apt_updates

    - name: Display apt update history
      debug:
        msg: "{{ apt_updates.stdout_lines }}"
