---
- name: Check for CentOS machines in inventory
  hosts: all  # Specify the group or hosts you want to check

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Display inventory name if CentOS
      debug:
        msg: "Inventory name '{{ inventory_hostname }}' is CentOS"
      when: ansible_distribution == 'CentOS'
