---
- name: Create a VM from a template using DHCP network
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "10.100.39.2"
    vcenter_username: "g.burucuasrvadm"
    vcenter_password: "ElcucuGerardin1390$"
    validate_certs: false
    vm_name: "new-vm-from-awx-dhcp"

  tasks:
    - name: Deploy a VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "HST"
        folder: "/HST/vm/ROOT-VPS-CLIENTS/PROD-VPS"
        name: "{{ vm_name }}"
        template: "ubuntu24"
        cluster: "VPS"
        resource_pool: "ROOT-VPS-CLIENTS"
        state: poweredon
        networks:
          - name: "dVLAN-ADMIN-1366"
            type: dhcp
        hardware:
          memory_mb: 2048
          num_cpus: 2
        customization:
          hostname: "testgb-awx-dhcp"
          domain: "prod.lan"
      register: deploy_result

    - name: Wait for VMware Tools to report IP address
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "HST"
        name: "{{ vm_name }}"
      register: vm_info
      retries: 10
      delay: 15
      until: vm_info.instance.ip_address is defined and vm_info.instance.ip_address != ""

    - name: Show assigned IP address
      debug:
        msg: "VM IP address is {{ vm_info.instance.ip_address }}"
