---
- name: Create a VM from a template with two network interfaces
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks:
    - name: Deploy a VM from template with 2 NICs
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs | default(false) }}"
        datacenter: "HST"
        folder: "/HST/vm/ROOT-VPS-CLIENTS/MTSI"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        cluster: "VPS"
        resource_pool: "ROOT-VPS-CLIENTS"
        state: poweredon
        networks:
          - name: "dVLAN-ADMIN-1366"
            type: dhcp
            start_connected: true
          - name: "dVLAN-PROD-133"
            type: static
            ip: "{{ vm_ip }}"
            netmask: "255.255.255.128"
            gateway: "80.94.97.1"
            start_connected: true
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpu }}"
        customization:
          hostname: "{{ vm_name }}"
          domain: "prod.lan"
          dns_servers:
            - 195.78.26.211
            - 195.78.26.210
      register: deploy_result
