---
- name: Gather info from all VMs discovered in inventory
  hosts: all
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "10.100.39.2"
    vcenter_username: "g.burucuasrvadm"
    vcenter_password: "ElcucuGerardin1390$"
    validate_certs: false

  tasks:
    - name: Gather info for each VM from vCenter
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ inventory_hostname }}"
      register: vm_info

    - name: Show VM info
      debug:
        var: vm_info
