---
- name: Gather info from all VMs discovered in inventory
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware

  vars:
    vcenter_hostname: "10.100.39.2"
    vcenter_username: "g.burucuasrvadm"
    vcenter_password: "ElcucuGerardin1390$"
    validate_certs: false

  tasks:
    - name: Get list of all VMs
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        folder: "/HST/vm/ROOT-VPS-CLIENTS"
      register: all_vms

    - name: Show names of all VMs
      debug:
        msg: "{{ item.guest_name }}"
      loop: "{{ all_vms.virtual_machines }}"
